import { MedKitItem } from './types/MedKitItem'

export const ANIMATION_DURATION = 500

export const MEDKIT_ITEMS: MedKitItem[] = [
  {
    id: 1,
    name: 'Ligadura',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Uma ligadura é uma tira de material usada para envolver uma ferida ou lesão.',
    howToUse: 'Enrola a ligadura à volta da ferida para estancar o sangramento e protegê-la de infeções.',
    importantNotes: 'Garante que a ligadura não está demasiado apertada para evitar cortar a circulação.',
  },
  {
    id: 2,
    name: 'Antisético',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Uma substância líquida usada para desinfetar a pele e matar germes.',
    howToUse: 'Aplica numa compressa de gaze e limpa suavemente a área ao redor da ferida.',
    importantNotes: 'Pode causar uma leve sensação de ardor no momento da aplicação.',
  },
  {
    id: 3,
    name: 'Compressas de Gaze',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Almofadas de tecido fino e arejado usadas para cobrir feridas maiores.',
    howToUse: 'Coloca a gaze sobre a ferida e fixa-a com fita adesiva médica ou uma ligadura.',
    importantNotes: 'Substitui a gaze regularmente se ficar húmida ou suja.',
  },
  {
    id: 4,
    name: 'Tesoura de Pontas Redondas',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Uma ferramenta de corte com pontas rombas para evitar ferimentos acidentais.',
    howToUse: 'Usa para cortar ligaduras, fita adesiva ou vestuário que esteja a cobrir uma lesão.',
    importantNotes: 'Mantém as lâminas limpas e desinfetadas.',
  },
  {
    id: 5,
    name: 'Luvas de Nitrilo',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Luvas descartáveis que protegem tanto o socorrista como o paciente.',
    howToUse: 'Calça as luvas antes de tocar em qualquer ferida ou fluido corporal.',
    importantNotes: 'Deita fora após cada utilização; não as reutilizes.',
  },
  {
    id: 6,
    name: 'Termómetro Digital',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Um dispositivo eletrónico usado para medir a temperatura corporal.',
    howToUse: 'Coloca sob a língua ou na axila e aguarda pelo sinal sonoro.',
    importantNotes: 'Desinfeta a ponta do termómetro antes e depois de cada uso.',
  },
  {
    id: 7,
    name: 'Pomada Antibiótica',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Uma pomada usada para prevenir infeções em cortes e arranhões.',
    howToUse: 'Aplica uma camada fina sobre a ferida limpa antes de cobri-la com uma ligadura.',
    importantNotes: 'Evita o contacto com os olhos e mucosas.',
  },
  {
    id: 8,
    name: 'Fita Adesiva Médica',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Uma fita adesiva especialmente desenhada para uso médico.',
    howToUse: 'Usa para fixar gazes ou ligaduras sobre feridas.',
    importantNotes: 'Certifica-te de que a pele está limpa e seca antes de aplicar a fita.',
  },
  {
    id: 9,
    name: 'Termómetro Digital',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Um dispositivo eletrónico usado para medir a temperatura corporal.',
    howToUse: 'Coloca sob a língua ou na axila e aguarda pelo sinal sonoro.',
    importantNotes: 'Desinfeta a ponta do termómetro antes e depois de cada uso.',
  },
  {
    id: 10,
    name: 'Pomada Antibiótica',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Uma pomada usada para prevenir infeções em cortes e arranhões.',
    howToUse: 'Aplica uma camada fina sobre a ferida limpa antes de cobri-la com uma ligadura.',
    importantNotes: 'Evita o contacto com os olhos e mucosas.',
  },
  {
    id: 11,
    name: 'Fita Adesiva Médica',
    imageUrl: '/images/no_image.jpg',
    whatIsIt: 'Uma fita adesiva especialmente desenhada para uso médico.',
    howToUse: 'Usa para fixar gazes ou ligaduras sobre feridas.',
    importantNotes: 'Certifica-te de que a pele está limpa e seca antes de aplicar a fita.',
  },
]
